const asmaNabi = [
    { number: 1, name: "مُحَمَّد", transliteration: "Muhammad", meaning: "The Highly Praised" },
    { number: 2, name: "أَحْمَد", transliteration: "Ahmad", meaning: "The Most Commendable" },
    { number: 3, name: "حَامِد", transliteration: "Hamid", meaning: "The Praiser" },
    { number: 4, name: "مَحْمُود", transliteration: "Mahmud", meaning: "The Praised One" },
    { number: 5, name: "قَاسِم", transliteration: "Qasim", meaning: "The Distributor" },
    { number: 6, name: "عَاقِب", transliteration: "Aqib", meaning: "The Last in Succession" },
    { number: 7, name: "فَاتِح", transliteration: "Fatih", meaning: "The Opener" },
    { number: 8, name: "خَاتِم", transliteration: "Khatim", meaning: "The Seal (of Prophets)" },
    { number: 9, name: "حَاشِر", transliteration: "Hashir", meaning: "The Gatherer" },
    { number: 10, name: "مَاحِي", transliteration: "Mahi", meaning: "The Effacer (of Kufr)" },
    { number: 11, name: "دَاعِي", transliteration: "Da'i", meaning: "The Caller (to Allah)" },
    { number: 12, name: "سِرَاج", transliteration: "Siraj", meaning: "The Lamp" },
    { number: 13, name: "مُنِير", transliteration: "Munir", meaning: "The Radiant" },
    { number: 14, name: "بَشِير", transliteration: "Bashir", meaning: "The Bringer of Good Tidings" },
    { number: 15, name: "نَذِير", transliteration: "Nadhir", meaning: "The Warner" },
    { number: 16, name: "رَؤُوف", transliteration: "Ra'uf", meaning: "The Compassionate" },
    { number: 17, name: "رَحِيم", transliteration: "Rahim", meaning: "The Merciful" },
    { number: 18, name: "خَلِيل", transliteration: "Khalil", meaning: "The Close Friend" },
    { number: 19, name: "حَبِيب", transliteration: "Habib", meaning: "The Beloved" },
    { number: 20, name: "مُصْطَفَى", transliteration: "Mustafa", meaning: "The Chosen One" },
    { number: 21, name: "مُجْتَبَى", transliteration: "Mujtaba", meaning: "The Selected" },
    { number: 22, name: "مُرْتَضَى", transliteration: "Murtada", meaning: "The Well-Pleasing" },
    { number: 23, name: "مُخْتَار", transliteration: "Mukhtar", meaning: "The Preferred" },
    { number: 24, name: "نَصِير", transliteration: "Nasir", meaning: "The Helper" },
    { number: 25, name: "مَنْصُور", transliteration: "Mansur", meaning: "The Victorious" },
    { number: 26, name: "طَهَ", transliteration: "Taha", meaning: "Taha (Quranic Title)" },
    { number: 27, name: "يَاسِين", transliteration: "Yasin", meaning: "Yasin (Quranic Title)" },
    { number: 28, name: "مُزَّمِّل", transliteration: "Muzzammil", meaning: "The Enwrapped" },
    { number: 29, name: "مُدَّثِّر", transliteration: "Muddaththir", meaning: "The Cloaked" },
    { number: 30, name: "شَفِيع", transliteration: "Shafi'", meaning: "The Intercessor" },
    { number: 31, name: "مُشَفَّع", transliteration: "Mushaffa'", meaning: "The One whose Intercession is Accepted" },
    { number: 32, name: "صَادِق", transliteration: "Sadiq", meaning: "The Truthful" },
    { number: 33, name: "مَصْدُوق", transliteration: "Masduq", meaning: "The Confirmed in Truth" },
    { number: 34, name: "أَمِين", transliteration: "Amin", meaning: "The Trustworthy" },
    { number: 35, name: "مَأْمُون", transliteration: "Ma'mun", meaning: "The Trusted" },
    { number: 36, name: "طَاهِر", transliteration: "Tahir", meaning: "The Pure" },
    { number: 37, name: "مُطَهَّر", transliteration: "Mutahhar", meaning: "The Purified" },
    { number: 38, name: "طَيِّب", transliteration: "Tayyib", meaning: "The Good" },
    { number: 39, name: "سَيِّد", transliteration: "Sayyid", meaning: "The Master" },
    { number: 40, name: "رَسُول", transliteration: "Rasul", meaning: "The Messenger" },
    { number: 41, name: "نَبِيّ", transliteration: "Nabi", meaning: "The Prophet" },
    { number: 42, name: "رَسُولُ الرَّحْمَة", transliteration: "Rasul-ur-Rahmah", meaning: "Messenger of Mercy" },
    { number: 43, name: "قَيِّم", transliteration: "Qayyim", meaning: "The Straight" },
    { number: 44, name: "جَامِع", transliteration: "Jami'", meaning: "The Collector" },
    { number: 45, name: "مُقْتَفِي", transliteration: "Muqtafi", meaning: "The Follower" },
    { number: 46, name: "مُقَفِّي", transliteration: "Muqaffi", meaning: "The Last in Succession" },
    { number: 47, name: "كَامِل", transliteration: "Kamil", meaning: "The Perfect" },
    { number: 48, name: "إِكْلِيل", transliteration: "Iklil", meaning: "The Crown" },
    { number: 49, name: "مُدَثِّر", transliteration: "Mudaththir", meaning: "The Covered" },
    { number: 50, name: "عَبْدُ اللَّه", transliteration: "Abdullah", meaning: "Servant of Allah" },
    { number: 51, name: "حَبِيبُ اللَّه", transliteration: "Habibullah", meaning: "Beloved of Allah" },
    { number: 52, name: "صَفِيُّ اللَّه", transliteration: "Safiyullah", meaning: "Chosen of Allah" },
    { number: 53, name: "نَجِيُّ اللَّه", transliteration: "Najiyullah", meaning: "Confident of Allah" },
    { number: 54, name: "كَلِيمُ اللَّه", transliteration: "Kalimullah", meaning: "Speaker of Allah" },
    { number: 55, name: "خَاتَمُ الأَنْبِيَاء", transliteration: "Khatam-ul-Anbiya", meaning: "Seal of the Prophets" },
    { number: 56, name: "خَاتَمُ الرُّسُل", transliteration: "Khatam-ur-Rusul", meaning: "Seal of the Messengers" },
    { number: 57, name: "مُحْيِي", transliteration: "Muhyi", meaning: "The Reviver" },
    { number: 58, name: "مُنْجِي", transliteration: "Munji", meaning: "The Savior" },
    { number: 59, name: "نَاطِق", transliteration: "Natiq", meaning: "The Speaker" },
    { number: 60, name: "شَاهِد", transliteration: "Shahid", meaning: "The Witness" },
    { number: 61, name: "شَهِيد", transliteration: "Shaheed", meaning: "The Witnesser" },
    { number: 62, name: "مَشْهُود", transliteration: "Mashhud", meaning: "The Witnessed" },
    { number: 63, name: "نُور", transliteration: "Nur", meaning: "The Light" },
    { number: 64, name: "بُرْهَان", transliteration: "Burhan", meaning: "The Proof" },
    { number: 65, name: "حُجَّة", transliteration: "Hujjah", meaning: "The Evidence" },
    { number: 66, name: "مُطِيع", transliteration: "Muti'", meaning: "The Obedient" },
    { number: 67, name: "مُذَكِّر", transliteration: "Mudhakkir", meaning: "The Reminder" },
    { number: 68, name: "وَاعِظ", transliteration: "Wa'iz", meaning: "The Preacher" },
    { number: 69, name: "هَادِي", transliteration: "Hadi", meaning: "The Guide" },
    { number: 70, name: "مَهْدِيّ", transliteration: "Mahdi", meaning: "The Rightly Guided" },
    { number: 71, name: "حَقّ", transliteration: "Haqq", meaning: "The Truth" },
    { number: 72, name: "مُبِين", transliteration: "Mubin", meaning: "The Clear" },
    { number: 73, name: "مُصَدِّق", transliteration: "Musaddiq", meaning: "The Asserter of Truth" },
    { number: 74, name: "شَكُور", transliteration: "Shakur", meaning: "The Most Thankful" },
    { number: 75, name: "وَلِيّ", transliteration: "Wali", meaning: "The Guardian/Friend" },
    { number: 76, name: "كَرِيم", transliteration: "Karim", meaning: "The Noble/Generous" },
    { number: 77, name: "مَكِين", transliteration: "Makin", meaning: "The Firm/Established" },
    { number: 78, name: "مَتِين", transliteration: "Matin", meaning: "The Strong" },
    { number: 79, name: "مُبْلِغ", transliteration: "Mubligh", meaning: "The Conveyor" },
    { number: 80, name: "مُؤْمِن", transliteration: "Mu'min", meaning: "The Believer" },
    { number: 81, name: "رَحْمَةٌ لِلْعَالَمِين", transliteration: "Rahmat-lil-Alamin", meaning: "Mercy for the Worlds" },
    { number: 82, name: "شَافِي", transliteration: "Shafi", meaning: "The Healer" },
    { number: 83, name: "وَاصِل", transliteration: "Wasil", meaning: "The Connector" },
    { number: 84, name: "مَوْصُول", transliteration: "Mawsul", meaning: "The Connected" },
    { number: 85, name: "سَابِق", transliteration: "Sabiq", meaning: "The Foremost" },
    { number: 86, name: "سَائِق", transliteration: "Sa'iq", meaning: "The Driver (to Jannah)" },
    { number: 87, name: "كَافِي", transliteration: "Kafi", meaning: "The Sufficient" },
    { number: 88, name: "مُكْتَفِي", transliteration: "Muktafi", meaning: "The Content" },
    { number: 89, name: "بَالِغ", transliteration: "Baligh", meaning: "The Reacher" },
    { number: 90, name: "رَاضِي", transliteration: "Radi", meaning: "The Pleased" },
    { number: 91, name: "مَرْضِيّ", transliteration: "Mardiy", meaning: "The Pleasing" },
    { number: 92, name: "مُقَدَّم", transliteration: "Muqaddam", meaning: "The Advanced/First" },
    { number: 93, name: "مُؤَخَّر", transliteration: "Mu'akhkhar", meaning: "The Last (in time)" },
    { number: 94, name: "فَاضِل", transliteration: "Fadil", meaning: "The Virtuous" },
    { number: 95, name: "مُفَضَّل", transliteration: "Mufaddal", meaning: "The Favored" },
    { number: 96, name: "شَكِير", transliteration: "Shakir", meaning: "The Grateful" },
    { number: 97, name: "ذَاكِر", transliteration: "Dhakir", meaning: "The Rememberer" },
    { number: 98, name: "خَطِيب", transliteration: "Khatib", meaning: "The Orator" },
    { number: 99, name: "أَبُو الْقَاسِم", transliteration: "Abu al-Qasim", meaning: "Father of Qasim" }
];
